version: 2

updates:
  # Auto-upgrade Github Actions versions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
    # Add labels manually due to Dependabot secrets issues
    # see https://github.com/dependabot/dependabot-core/issues/3253
      - "kind/dependency"
      - "area/automation"
      - "bump:patch"

  # Auto-upgrade Go dependencies
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      # Add labels manually due to Dependabot secrets issues
      # see https://github.com/dependabot/dependabot-core/issues/3253
      - "kind/dependency"
      - "area/go"
      - "area/automation"
      - "bump:patch"

  # Auto-upgrade Docker image tags
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    labels:
      # Add labels manually due to Dependabot secrets issues
      # see https://github.com/dependabot/dependabot-core/issues/3253
      - "kind/dependency"
      - "area/go"
      - "area/automation"
      - "bump:patch"
