image: gitpod/workspace-full

ports:
  - port: 5003
    onOpen: open-preview

tasks:
  - command: go run .

  - command: ./assets/welcome.sh
    openMode: split-right

vscode:
  extensions:
    - golang.go
